### ISSUE TITLE
otp_login(email, password, otpnumber) not working

### ISSUE THREAD

**Issue by sakshamgulati** [yusuf8ahmed/Wsimple#55]
Tried loggin in multiple times but the function is throwing an exception

WSOTPLoginError                           Traceback (most recent call last)
<ipython-input-7-7348530c2dad> in <module>
      7     # Exception occurs on one time password only.
      8     otpnumber = int(input("Enter otpnumber: \n>>>"))
----> 9     ws = Wsimple.otp_login(email, password, otpnumber)
     10     tokens = ws.tokens
     11 

~\Anaconda3\lib\site-packages\wsimple\api\api.py in otp_login(cls, email, password, otp_number, verbose)
    179         constructor: login with a otp code:
    180         """
--> 181         wsimple = cls(email, password, otp_mode=True, otp_number=int(otp_number))
    182         return wsimple
    183 

~\Anaconda3\lib\site-packages\wsimple\api\api.py in __init__(self, email, password, otp_number, otp_mode, public_mode, oauth_mode, verbose_mode, tokens)
    149                     del r
    150                 else:
--> 151                     if otp_mode: raise WSOTPLoginError
    152                     raise LoginError
    153 

WSOTPLoginError: An Wealthsimple otp login error happend, please try again

**Comment by yusuf8ahmed** [comment]
Hi, Thank you for opening this issue. Wealthsimple API only sends an OTP number to your email after you try to login with the correct password and email.

This is why I suggest for people to use this try-catch block.

```python
email = str(input("Enter email: \n>>>"))  
password = str(input("Enter password: \n>>>")). 
try:  
    ws = Wsimple(email, password) # login to Wealthsimple  
    tokens = ws.tokens # token are the keys to your account   
except WSOTPUser:  
    # Exception occurs on one time password only.  
    otpnumber = int(input("Enter otpnumber: \n>>>")). 
    ws = Wsimple.otp_login(email, passw, otpnumber). 
    tokens = ws.tokens  
```

**Comment by sakshamgulati** [comment]
I tried using your code as well. Now it throws me a WSOTPLoginError

WSOTPLoginError: An Wealthsimple otp login error happend, please try again

Please let me know the way forward

**Comment by yusuf8ahmed** [comment]
Hi Sakshamgulati, this is the new way to login in.

```python
from wsimple.api import Wsimple

def get_otp():
    return input("Enter otpnumber: \n>>>")

email = str(input("Enter email: \n>>>"))
password = str(input("Enter password: \n>>>"))

ws = Wsimple(email, password, otp_callback=get_otp) 
```
