### ISSUE TITLE
HTTP 403 Error when trying to login

### ISSUE THREAD

**Issue by AdhamFarag** [yusuf8ahmed/Wsimple#59]
Is anyone getting a login 403 error?

**Comment by yusuf8ahmed** [comment]
I think wealthsimple changed the login process

**Comment by mrtanishqbhatia** [comment]
Looking forward for you to resolve the bug, asap. 👍

**Comment by Zechtitus** [comment]
just encountered same thing on a different python wsimple api - I'll keep watch here and if were stuck I'll look at adding a PR.

**Comment by yusuf8ahmed** [comment]
@Zechtitus a PR would be amazing as I will be busy for the next few weeks

**Comment by Zechtitus** [comment]
there is one other guy working on issue here - https://github.com/ahmedsakr/wstrade-api/issues/96
Will see what he churns up. He is right on the cloudflare security

**Comment by yusuf8ahmed** [comment]
Great NEWS guys I found a way to log in

**Comment by AdhamFarag** [comment]
> Great NEWS guys I found a way to log in

that's great!! will you be updating the repo soon or can you share how you managed to do that, please?

**Comment by ahmedsakr** [comment]
> 
> 
> there is one other guy working on issue here - [ahmedsakr/wstrade-api#96](https://github.com/ahmedsakr/wstrade-api/issues/96)
> Will see what he churns up. He is right on the cloudflare security

I just merged my fixes to wstrade-api and it's available in `v1.7.0` :)

**Comment by Zechtitus** [comment]
Thanks! Nice to get the bot back working

**Comment by joeyorlando** [comment]
Hello, cross-posting on here as well. Just opened a [PR](https://github.com/seansullivan44/Wealthsimple-Trade-Python/pull/15) in the other Python client library. Swaps out `requests.Session` for [`cloudscraper.Cloudscraper`](https://github.com/venomous/cloudscraper) (instance of `requests.Session`). Got things working with that :)

**Comment by joeyorlando** [comment]
on an aside, could it be worthwhile merging these two Python client libraries, into a consolidated/"unofficially official" Python client library?

**Comment by yusuf8ahmed** [comment]
Would have no problem merging his project somehow into mine, also working on a new release with a working fix for the login problems and a couple of other goodies like accessing dictionaries with dot notation (like Javascript) and a more organized HTTP request system - currently on branch [api_v2](lhttps://github.com/yusuf8ahmed/Wsimple/tree/api_v2)

**Comment by joeyorlando** [comment]
@yusuf8ahmed if it's helpful for the login related issues, see my PR [here](https://github.com/seansullivan44/Wealthsimple-Trade-Python/pull/15/files)

**Comment by yusuf8ahmed** [comment]
also, you guys might see a folder called wsimple-desktop could be a new part of this project ???

**Comment by mysterylektro** [comment]
Hello guys. First off - big thank you for making this public! I have used the api_v2 branch to successfully log in and send in buy / sell orders, and cancel them entirely from within the framework you guys have built. I did have to modify line 330 of api.py to get it working, as I think you are adding different URL sources (base vs base public etc.)

Most of the WSimple class functions require passing in the tokens, however the tokens are a member of the class itself. Is there a reason for this?

Cheers!

**Comment by yusuf8ahmed** [comment]
It was an intentional design choice as I was planning on making it work with a web app(which I am still planning on building), also I am currently working on my local branch with a version of Wsimple that manages tokens after a flag on the Wsimple is set True. Still needs some little testing and more development though

**Comment by Korpip** [comment]
So where are we at here?
Is this patch being rolled into the main branch?
The last update to V2 is 12 days and this this thread talks about changes 6 days ago.

**Comment by yusuf8ahmed** [comment]
Okay hello, guys v2 is finished and just needs a little more testing so you guys can pull it and test in your environment, if you have any problems report them here:

Changelog:
- Change login process from using an exception to a callback function:

```python
from wsimple.api import Wsimple

def get_otp():
    return int(input("Enter otpnumber: \n>>>"))

email = str(input("Enter email: \n>>>"))
password = str(input("Enter password: \n>>>"))

ws = Wsimple(email, password, otp_callback=get_otp) 
```
- resolved 403 http issue when logging in
- tokens are new internally managed but tokens are still a keyword argument.

**Comment by yusuf8ahmed** [comment]
Update on api_v2, wsimple is officially on v2, the branch api_v2 will be merged with master very soon.

To update:
`pip install -U wsimple`

To install the latest version:
`pip install wsimple`

**Comment by Zechtitus** [comment]
I just started seeing issues again with https://github.com/seansullivan44/Wealthsimple-Trade-Python - are you guys seeing similar?

**Comment by ahmedsakr** [comment]
I just tested https://github.com/ahmedsakr/wstrade-api and it's still working.

**Comment by yusuf8ahmed** [comment]
@Zechtitus @ahmedsakr  wsimple is still working, no login errors, also access real-time data via websockets should be working fully in the next update.

**Comment by yusuf8ahmed** [comment]
Hi guys, you can start testing api_v2 by upgrading wsimple.

upgrade:
`pip install -U wsimple`

install:
`pip install wsimple`

**Comment by yusuf8ahmed** [comment]
Okay guys api_v2 is officially finished and has been merged with master, thank you @AdhamFarag for opening this issue. if any of you guys have a problem feel free to open another issue. :) pz out

- also you might wanna check out the real-time data example here been working on making to goood [realtime](https://github.com/yusuf8ahmed/Wsimple/blob/master/example/realtime.py)

**Comment by ahmedsakr** [comment]
Congrats 🔥 🔥 v2 looks really good!

Also just to clarify on the websocket, it's real-time in the sense that it's a continuous stream of data, but the stock quotes are still 15-mins delayed (because WS Trade doesn't support real-time quotes yet). Crypto quotes might be close to real-time, tho.
